export const USERS_FETCH_START = "USERS_FETCH_START"
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS"
export const USERS_FETCH_FAIL = "USERS_FETCH_FAIL"

export const USERS_FILTER = 'USERS_FILTER'


export const USER_FETCH_START = "USER_FETCH_START"
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"
export const USER_FETCH_FAIL = "USER_FETCH_FAIL"

export const USERS_RESET = "USERS_RESET"